# -*- coding: utf-8 -*-
"""final_jupyter_covid19-5-2-1-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/eceyy/6a4861905095f8b94285f8ab0091bc3a/final_jupyter_covid19-5-2-1-1.ipynb

<h1>Analysis of Global COVID-19 Pandemic Data</h1>

Estimated time needed: **90** minutes

## Overview:

There are 10 tasks in this final project. All tasks will be graded by your peers who are also completing this assignment within the same session.

You need to submit the following the screenshot for the code and output for each task for review.

If you need to refresh your memories about specific coding details, you may refer to previous hands-on labs for code examples.
"""

install.packages("httr")
install.packages("rvest")

library(httr)
library(rvest)

"""Note: if you can import above libraries, please use install.packages() to install them first.

## TASK 1: Get a `COVID-19 pandemic` Wiki page using HTTP request

First, let's write a function to use HTTP request to get a public COVID-19 Wiki page.

Before you write the function, you can open this public page from this 

URL https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country using a web browser.

The goal of task 1 is to get the html page using HTTP request (`httr` library)
"""

get_wiki_covid19_page <- function() {
    
  # Our target COVID-19 wiki page URL is: https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country  
  # Which has two parts: 
    # 1) base URL `https://en.wikipedia.org/w/index.php  
    # 2) URL parameter: `title=Template:COVID-19_testing_by_country`, seperated by question mark ?
    
  # Wiki page base
  wiki_base_url <- "https://en.wikipedia.org/w/index.php"
  # You will need to create a List which has an element called `title` to specify which page you want to get from Wiki
  # in our case, it will be `Template:COVID-19_testing_by_country`
  # - Use the `GET` function in httr library with a `url` argument and a `query` arugment to get a HTTP response
  # in our case, it will be `Template:COVID-19_testing_by_country`
  query_wiki <- list(title = "Template:COVID-19_testing_by_country")
  get_wiki_covid19_page <- GET(wiki_base_url, query=query_wiki)
  # Use the `return` function to return the response
  return(get_wiki_covid19_page)
}

"""Call the `get_wiki_covid19_page` function to get a http response with the target html page

"""

# Call the get_wiki_covid19_page function and print the response
get_wiki_covid19_page()

"""## TASK 2: Extract COVID-19 testing data table from the wiki HTML page

On the COVID-19 testing wiki page, you should see a data table `<table>` node contains COVID-19 testing data by country on the page:

<a href="https://cognitiveclass.ai/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0101ENCoursera889-2022-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M5_Final/images/covid-19-by-country.png" width="400" align="center">
</a>

Note the numbers you actually see on your page may be different from above because it is still an on-going pandemic when creating this notebook.

The goal of task 2 is to extract above data table and convert it into a data frame

Now use the `read_html` function in rvest library to get the root html node from response
"""

# Get the root html node from the http response in task 1 
simple_html_text <- "
<html>
    <body>
        <p>This is a test html page</p>
    </body>
</html>"
root_node <- read_html(simple_html_text)
root_node

"""Get the first table in the HTML root node using `html_node` function

"""

html_node <- html_node(root_node,"table")
html_node

"""Read the table node as a data frame using `html_table` function

"""

# Read the table node and convert it into a data frame, and print the data frame for review
#table_url<-"https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country"
#root_node <-read_html(table_url)
#table_node<-html_node(root_node,"table")
data_frame<-html_table(table_node)
data_frame

"""## TASK 3: Pre-process and export the extracted data frame

The goal of task 3 is to pre-process the extracted data frame from the previous step, and export it as a csv file

Let's get a summary of the data frame
"""

# Print the summary of the data frame
output<-summary(data_frame)

output

"""As you can see from the summary, the columns names are little bit different to understand and some column data types are not correct. For example, the `Tested` column shows as `character`. 

As such, the data frame read from HTML table will need some pre-processing such as removing irrelvant columns, renaming columns, and convert columns into proper data types.

We have prepared a pre-processing function for you to conver the data frame but you can also try to write one by yourself
"""

preprocess_covid_data_frame <- function(data_frame) {
    
    shape <- dim(data_frame)

    # Remove the World row
    data_frame<-data_frame[!(data_frame$`Country or region`=="World"),]
    # Remove the last row
    data_frame <- data_frame[1:172, ]
    
    # We dont need the Units and Ref columns, so can be removed
    data_frame["Ref."] <- NULL
    data_frame["Units[b]"] <- NULL
    
    # Renaming the columns
    names(data_frame) <- c("country", "date", "tested", "confirmed", "confirmed.tested.ratio", "tested.population.ratio", "confirmed.population.ratio")
    
    # Convert column data types
    data_frame$country <- as.factor(data_frame$country)
    data_frame$date <- as.factor(data_frame$date)
    data_frame$tested <- as.numeric(gsub(",","",data_frame$tested))
    data_frame$confirmed <- as.numeric(gsub(",","",data_frame$confirmed))
    data_frame$'confirmed.tested.ratio' <- as.numeric(gsub(",","",data_frame$`confirmed.tested.ratio`))
    data_frame$'tested.population.ratio' <- as.numeric(gsub(",","",data_frame$`tested.population.ratio`))
    data_frame$'confirmed.population.ratio' <- as.numeric(gsub(",","",data_frame$`confirmed.population.ratio`))
    
    return(data_frame)
}

"""Call the `preprocess_covid_data_frame` function

"""

# call `preprocess_covid_data_frame` function and assign it to a new data frame
new_covid_data_frame<-preprocess_covid_data_frame(data_frame)

"""Get the summary of the processed data frame again

"""

# Print the summary of the processed data frame aga
summary(new_covid_data_frame)

"""After pre-processing, you can see the columns and columns names are simplified, and columns types are converted into correct types.

The data frame has following columns:

- **country** - The name of the country
- **date** - Reported date
- **tested** - Total tested cases by the reported date
- **confirmed** - Total confirmed cases by the reported date
- **confirmed.tested.ratio** - The ratio of confirmed cases to the tested cases
- **tested.population.ratio** - The ratio of tested cases to the population of the country
- **confirmed.population.ratio** - The ratio of confirmed cases to the population of the country

OK, we can call `write.csv()` function to save the csv file into a file.
"""

# Export the data frame to a csv file
write.csv(new_covid_data_frame,file='/resources/labs/RP0101EN/covid.csv')

"""Note for IBM Waston Studio, there is no traditional "hard disk" associated with a R workspace.

Even if you call `write.csv()` method to save the data frame as a csv file, it won't be shown in IBM Cloud Object Storage asset UI automatically.

However, you may still check if the `covid.csv` exists using following code snippet:

"""

# Get working directory
wd <- getwd()
# Get exported 
file_path <- paste(wd, sep="", "/covid.csv")
# File path
print(file_path)
file.exists(file_path)

"""**Optional Step**: If you have difficulties finishing above webscraping tasks, you may still continue with next tasks by downloading a provided csv file from here:

"""

## Download a sample csv file
# covid_csv_file <- download.file("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/dataset/covid.csv", destfile="covid.csv")
# covid_data_frame_csv <- read.csv("covid.csv", header=TRUE, sep=",")
covid_csv_file <- download.file("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/dataset/covid.csv", destfile="covid.csv")
covid_data_frame_csv <- read.csv("covid.csv", header=TRUE, sep=",")

"""## TASK 4: Get a subset of the extracted data frame

The goal of task 4 is to get the 5th to 10th rows from the data frame with only `country` and `confirmed` columns selected

"""

# Read covid_data_frame_csv from the csv file
covid_data_frame_csv<-read.csv("covid.csv")
# Get the 5th to 10th rows, with two "country" "confirmed" columns
covid_data_frame_csv[5:10,c("country","confirmed")]

"""## TASK 5: Calculate worldwide COVID testing positive ratio

The goal of task 5 is to get the total confirmed and tested cases worldwide, and try to figure the overall positive ratio using `confirmed cases / tested cases`

"""

# Get the total confirmed cases worldwide
confirmed<-sum(covid_data_frame_csv[,'confirmed'])
print(confirmed)
# Get the total tested cases worldwide
tested<-sum(covid_data_frame_csv[,'tested'])
print(tested)
# Get the positive ratio (confirmed / tested)
positive_ratio<-confirmed/tested
print(positive_ratio)

"""## TASK 6: Get a country list which reported their testing data 

The goal of task 6 is to get a catalog or sorted list of countries who have reported their COVID-19 testing data

"""

# Get the `country` column
country<-country_data_frame_csv[,'country']
# Check its class (should be Factor)
class(country)
# Conver the country column into character so that you can easily sort them
character<-as.character(country)
# Sort the countries AtoZ
sorted_list<-sort(character)
# Sort the countries ZtoA
reverse_sorted_list<-sort(sorted_list, decreasing=TRUE)
# Print the sorted ZtoA list
print(reverse_sorted_list)

"""## TASK 7: Identify countries names with a specific pattern

The goal of task 7 is using a regular expression to find any countires start with `United`

"""

# Use a regular expression `United.+` to find matches
matches<-grep("United.+", covid_data_frame_csv[,'country'],value=TRUE)
# Print the matched country names
print(matches)

"""## TASK 8: Pick two countries you are interested, and then review their testing data

The goal of task 8 is to compare the COVID-19 test data between two countires, you will need to select two rows from the dataframe, and select `country`, `confirmed`, `confirmed-population-ratio` columns

"""

# Select a subset (should be only one row) of data frame based on a selected country name and columns

subset<-covid_data_frame_csv[covid_data_frame_csv$country %in% c('Turkey'), c('country', 'confirmed', 'confirmed.population.ratio')]

# Select a subset (should be only one row) of data frame based on a selected country name and columns
subset1<-covid_data_frame_csv[covid_data_frame_csv$country %in% c('United States'), c('country', 'confirmed', 'confirmed.population.ratio')]

subset
subset1

"""## TASK 9: Compare which one of the selected countries has a larger ratio of confirmed cases to population

The goal of task 9 is to find out which country you have selected before has larger ratio of confirmed cases to population, which may indicate that country has higher COVID-19 infection risk

"""

# Use if-else statement
# if (check which confirmed.population value is greater) {
#first_country<-readline(prompt="first country:")
#second_country<-readline(prompt="second country:")

#if(text[country,"Albania"]$confirmed.population > text[country,"Algeria"]$confirmed.population){
#    print()
if(subset(covid_data_frame_csv,country=="Albania") %in% text$confirmed.population>subset(covid_data_frame_csv,country=="Algeria") %in% text$confirmed.population) {
    
        print("first country has higher Covid-19 infection risk")
# } else {
 } else{
#     print()
        print("second country has higher Covid-19 infection risk")

 # }
  }

"""## TASK 10: Find countries with confirmed to population ratio rate less than a threshold

The goal of task 10 is to find out which countries have the confirmed to population ratio less than 1%, it may indicate the risk of those countries are relatively low

"""

# Get a subset of any countries with `confirmed.population.ratio` less than the threshold
subset(covid_data_frame_csv,subset=confirmed.population.ratio<1)

